### ISSUE TITLE
flutter iOS Deep link callbacks not working when the app is closed

### ISSUE THREAD

**Issue by yugalkalyan** [singular-labs/Singular-Flutter-SDK#29]
I am using singular_flutter_sdk: ^1.0.12 for deep link in my flutter application , in android its working fine but in iOS, when application is already running in background it works but when application is initialised by tapping on the link it only works for first time and when I tap again on link it opens the applications from the background and does not navigate to specific screen .

it should navigate to screen every time when initialising the app using link.

**Comment by shefdanny** [comment]
Hey @yugalkalyan , updating to a newer version should fix this issue

**Comment by yugalkalyan** [comment]
Hi, @shefdanny , after updating to new version issue is not fixed its behaviour to handle the application is same as I mentioned before

**Comment by shefdanny** [comment]
please contact us through the Help section in the web app.
